<?php

declare(strict_types=1);

namespace App\Engine\Database;

use App\Engine\Database\Structure\Column;
use App\Engine\Database\Structure\ColumnType;

/**
 * PostgreSQL.
 *
 * Standard quoting, paging and savepoints. Placeholders stay `?`: PDO rewrites
 * them into PostgreSQL's own numbered form, and writing `$1` here would only
 * confuse it.
 */
final class PostgresGrammar extends Grammar
{
    public function driver(): string
    {
        return 'pgsql';
    }

    public function supports(Capability $capability): bool
    {
        return match ($capability) {
            Capability::Savepoints => true,
            Capability::Returning => true,
            Capability::Upsert => true,
            Capability::RightJoin => true,
            Capability::TransactionalDdl => true,
        };
    }

    /**
     * Every level. READ UNCOMMITTED runs as READ COMMITTED -- PostgreSQL never
     * shows uncommitted rows -- which is stricter than asked, never weaker.
     * The standard compileIsolation() is PostgreSQL's own.
     */
    public function supportsIsolation(IsolationLevel $level): bool
    {
        return true;
    }

    /** The wire protocol counts parameters in two bytes. */
    public function maxBindings(): int
    {
        return 65535;
    }

    public function compileTableExists(string $table): array
    {
        return [
            'sql' => 'SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?',
            'bindings' => [$table],
        ];
    }

    /**
     * An advisory lock is keyed by a number, not a name, so the name is hashed
     * to one: the same name, the same key, on every machine.
     */
    public function compileAcquireLock(string $name): array
    {
        return ['sql' => 'SELECT CASE WHEN pg_try_advisory_lock(?) THEN 1 ELSE 0 END', 'bindings' => [\crc32($name)]];
    }

    public function compileReleaseLock(string $name): array
    {
        return ['sql' => 'SELECT pg_advisory_unlock(?)', 'bindings' => [\crc32($name)]];
    }

    /** An identity column, the standard's own, rather than SERIAL and its separate sequence. */
    protected function idColumn(): string
    {
        return 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
    }

    protected function columnType(Column $column): string
    {
        return match ($column->type) {
            ColumnType::Id, ColumnType::BigInteger => 'BIGINT',
            ColumnType::Integer => 'INTEGER',
            ColumnType::Decimal => \sprintf('NUMERIC(%d,%d)', $column->precision, $column->scale),
            ColumnType::String => \sprintf('VARCHAR(%d)', $column->length),
            ColumnType::Text => 'TEXT',
            ColumnType::Boolean => 'BOOLEAN',
            ColumnType::Date => 'DATE',
            ColumnType::DateTime => 'TIMESTAMP(6)',
            ColumnType::Binary => 'BYTEA',
        };
    }

    /** A real boolean, which will not take 1 and 0 as a default. */
    protected function booleanLiteral(bool $value): string
    {
        return $value ? 'TRUE' : 'FALSE';
    }
}
