<?php

declare(strict_types=1);

namespace App\Tests\Unit\Database;

use App\Engine\Database\Connection;
use App\Engine\Database\ConnectionConfig;
use App\Engine\Database\DatabaseException;
use App\Engine\Database\Grammar;
use App\Engine\Database\Structure\Table;
use App\Tests\Support\TestCase;
use PHPUnit\Framework\Attributes\DataProvider;

/**
 * The table builder: what each dialect writes, what it refuses, and that SQLite
 * runs it. DialectConformanceTest runs the same tables on the other databases.
 */
final class TableBuilderTest extends TestCase
{
    /** @return list<string> */
    private static function compile(string $driver, \Closure $define, string $name = 'invoices'): array
    {
        $table = new Table($name);
        $define($table);

        return Grammar::for($driver)->compileCreateTable(
            $table,
            static fn(string $value): string => "'" . \str_replace("'", "''", $value) . "'",
        );
    }

    /** @return list<string> */
    private static function alter(string $driver, \Closure $define, string $name = 'invoices'): array
    {
        $table = new Table($name, altering: true);
        $define($table);

        return Grammar::for($driver)->compileAlterTable(
            $table,
            static fn(string $value): string => "'" . \str_replace("'", "''", $value) . "'",
        );
    }

    private static function invoices(Table $table): void
    {
        $table->id();
        $table->bigInteger('customer_id')->index();
        $table->string('number', 30)->unique();
        $table->decimal('total', 12, 2)->default('0.00');
        $table->boolean('paid')->default(false);
        $table->dateTime('issued_at')->nullable();
        $table->foreign('customer_id')->references('customers')->onDelete('restrict');
    }

    private function sqlite(): Connection
    {
        return new Connection(ConnectionConfig::of('test', 'sqlite::memory:'));
    }

    // ---- what each dialect writes -------------------------------------------

    /** @return array<string, array{string, list<string>}> */
    public static function dialects(): array
    {
        return [
            'mysql' => ['mysql', [
                'CREATE TABLE `invoices` (`id` BIGINT AUTO_INCREMENT PRIMARY KEY, `customer_id` BIGINT NOT NULL, '
                . '`number` VARCHAR(30) NOT NULL, `total` DECIMAL(12,2) NOT NULL DEFAULT \'0.00\', '
                . '`paid` TINYINT(1) NOT NULL DEFAULT 0, `issued_at` DATETIME(6) NULL, '
                . 'CONSTRAINT `invoices_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) '
                . 'ON DELETE RESTRICT ON UPDATE NO ACTION) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
                'CREATE INDEX `invoices_customer_id_index` ON `invoices` (`customer_id`)',
                'CREATE UNIQUE INDEX `invoices_number_unique` ON `invoices` (`number`)',
            ]],
            'pgsql' => ['pgsql', [
                'CREATE TABLE "invoices" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "customer_id" BIGINT NOT NULL, '
                . '"number" VARCHAR(30) NOT NULL, "total" NUMERIC(12,2) NOT NULL DEFAULT \'0.00\', '
                . '"paid" BOOLEAN NOT NULL DEFAULT FALSE, "issued_at" TIMESTAMP(6) NULL, '
                . 'CONSTRAINT "invoices_customer_id_foreign" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") '
                . 'ON DELETE RESTRICT ON UPDATE NO ACTION)',
                'CREATE INDEX "invoices_customer_id_index" ON "invoices" ("customer_id")',
                'CREATE UNIQUE INDEX "invoices_number_unique" ON "invoices" ("number")',
            ]],
            'sqlite' => ['sqlite', [
                'CREATE TABLE "invoices" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "customer_id" INTEGER NOT NULL, '
                . '"number" TEXT NOT NULL, "total" NUMERIC NOT NULL DEFAULT \'0.00\', '
                . '"paid" INTEGER NOT NULL DEFAULT 0, "issued_at" TEXT NULL, '
                . 'CONSTRAINT "invoices_customer_id_foreign" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") '
                . 'ON DELETE RESTRICT ON UPDATE NO ACTION)',
                'CREATE INDEX "invoices_customer_id_index" ON "invoices" ("customer_id")',
                'CREATE UNIQUE INDEX "invoices_number_unique" ON "invoices" ("number")',
            ]],
            // RESTRICT is NO ACTION here: SQL Server has only the one.
            'sqlsrv' => ['sqlsrv', [
                'CREATE TABLE [invoices] ([id] BIGINT IDENTITY(1,1) PRIMARY KEY, [customer_id] BIGINT NOT NULL, '
                . '[number] NVARCHAR(30) NOT NULL, [total] DECIMAL(12,2) NOT NULL DEFAULT \'0.00\', '
                . '[paid] BIT NOT NULL DEFAULT 0, [issued_at] DATETIME2(6) NULL, '
                . 'CONSTRAINT [invoices_customer_id_foreign] FOREIGN KEY ([customer_id]) REFERENCES [customers] ([id]) '
                . 'ON DELETE NO ACTION ON UPDATE NO ACTION)',
                'CREATE INDEX [invoices_customer_id_index] ON [invoices] ([customer_id])',
                'CREATE UNIQUE INDEX [invoices_number_unique] ON [invoices] ([number])',
            ]],
        ];
    }

    /** @param list<string> $expected */
    #[DataProvider('dialects')]
    public function test_one_description_is_written_in_each_dialect(string $driver, array $expected): void
    {
        self::assertSame($expected, self::compile($driver, self::invoices(...)));
    }

    /** @return array<string, array{string, list<string>}> */
    public static function types(): array
    {
        return [
            'mysql' => ['mysql', ['INT', 'BIGINT', 'DECIMAL(8,3)', 'VARCHAR(255)', 'LONGTEXT', 'TINYINT(1)', 'DATE', 'DATETIME(6)', 'LONGBLOB']],
            'pgsql' => ['pgsql', ['INTEGER', 'BIGINT', 'NUMERIC(8,3)', 'VARCHAR(255)', 'TEXT', 'BOOLEAN', 'DATE', 'TIMESTAMP(6)', 'BYTEA']],
            'sqlite' => ['sqlite', ['INTEGER', 'INTEGER', 'NUMERIC', 'TEXT', 'TEXT', 'INTEGER', 'TEXT', 'TEXT', 'BLOB']],
            'sqlsrv' => ['sqlsrv', ['INT', 'BIGINT', 'DECIMAL(8,3)', 'NVARCHAR(255)', 'NVARCHAR(MAX)', 'BIT', 'DATE', 'DATETIME2(6)', 'VARBINARY(MAX)']],
        ];
    }

    /** @param list<string> $expected */
    #[DataProvider('types')]
    public function test_every_type_has_a_name_in_every_dialect(string $driver, array $expected): void
    {
        [$create] = self::compile($driver, static function (Table $table): void {
            $table->integer('a');
            $table->bigInteger('b');
            $table->decimal('c', 8, 3);
            $table->string('d');
            $table->text('e');
            $table->boolean('f');
            $table->date('g');
            $table->dateTime('h');
            $table->binary('i');
        });

        foreach ($expected as $type) {
            self::assertStringContainsString($type, $create, $driver);
        }
    }

    /** SQL Server alone counts NULLs as equal in a unique index; its index leaves them out. */
    public function test_a_nullable_unique_column_on_sql_server_lets_many_rows_hold_null(): void
    {
        $statements = self::compile('sqlsrv', static function (Table $table): void {
            $table->string('email')->nullable()->unique();
            $table->string('code')->unique();
            $table->string('region')->nullable();
            $table->unique('code', 'region');
        }, 'people');

        self::assertSame('CREATE UNIQUE INDEX [people_email_unique] ON [people] ([email]) WHERE [email] IS NOT NULL', $statements[1]);
        self::assertSame('CREATE UNIQUE INDEX [people_code_unique] ON [people] ([code])', $statements[2]);
        self::assertSame('CREATE UNIQUE INDEX [people_code_region_unique] ON [people] ([code], [region]) WHERE [region] IS NOT NULL', $statements[3]);
        self::assertStringNotContainsString('WHERE', self::compile('pgsql', static function (Table $table): void {
            $table->string('email')->nullable()->unique();
        }, 'people')[1]);
    }

    /**
     * A plain '...' is VARCHAR to SQL Server, in the server's code page, and
     * কলকাতা would reach the NVARCHAR column as question marks. CI caught it.
     */
    public function test_a_string_default_on_sql_server_is_a_unicode_literal(): void
    {
        [$create] = self::compile('sqlsrv', static function (Table $table): void {
            $table->string('city', 50)->default('কলকাতা');
            $table->decimal('total', 12, 2)->default('0.00');
        });

        self::assertStringContainsString("[city] NVARCHAR(50) NOT NULL DEFAULT N'কলকাতা'", $create);
        self::assertStringContainsString("[total] DECIMAL(12,2) NOT NULL DEFAULT '0.00'", $create);
        self::assertStringContainsString("DEFAULT 'কলকাতা'", self::compile('pgsql', static function (Table $table): void {
            $table->string('city', 50)->default('কলকাতা');
        })[0]);
    }

    /** A key that is not a counted id: a session id, a country code. */
    public function test_a_string_key_in_each_dialect(): void
    {
        $key = static function (Table $table): void {
            $table->string('code', 2)->primary();
            $table->string('name', 80)->default('');
        };

        self::assertStringStartsWith('CREATE TABLE `countries` (`code` VARCHAR(2) NOT NULL PRIMARY KEY, ', self::compile('mysql', $key, 'countries')[0]);
        self::assertStringStartsWith('CREATE TABLE "countries" ("code" VARCHAR(2) NOT NULL PRIMARY KEY, ', self::compile('pgsql', $key, 'countries')[0]);
        self::assertStringStartsWith('CREATE TABLE "countries" ("code" TEXT NOT NULL PRIMARY KEY, ', self::compile('sqlite', $key, 'countries')[0]);
        self::assertStringStartsWith('CREATE TABLE [countries] ([code] NVARCHAR(2) NOT NULL PRIMARY KEY, ', self::compile('sqlsrv', $key, 'countries')[0]);
        self::assertStringContainsString('[name] NVARCHAR(80) NOT NULL DEFAULT N\'\'', self::compile('sqlsrv', $key, 'countries')[0]);
    }

    /** @return array<string, array{\Closure(Table): mixed, string}> */
    public static function badKeys(): array
    {
        return [
            'two keys' => [static function (Table $t): void {
                $t->id();
                $t->string('code', 2)->primary();
            }, 'more than one key: id, code'],
            'a nullable key' => [static fn(Table $t) => $t->string('code', 2)->primary()->nullable(), 'a key cannot be NULL'],
            'a key on text' => [static fn(Table $t) => $t->text('body')->primary(), 'cannot be indexed'],
        ];
    }

    #[DataProvider('badKeys')]
    public function test_a_key_every_database_could_not_hold_is_refused(\Closure $define, string $message): void
    {
        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage($message);

        self::compile('pgsql', $define);
    }

    public function test_a_key_cannot_be_added_to_a_table_that_exists(): void
    {
        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage('a key cannot be added to a table that exists');

        self::alter('pgsql', static fn(Table $t) => $t->string('code', 2)->nullable()->primary());
    }

    public function test_a_name_too_long_for_postgresql_is_shortened_but_stays_distinct(): void
    {
        $table = new Table('a_rather_long_table_name_for_invoice_lines');
        $first = $table->nameFor(['customer_reference_number', 'region'], 'unique');
        $second = $table->nameFor(['customer_reference_number', 'regions'], 'unique');

        self::assertLessThanOrEqual(60, \strlen($first));
        self::assertNotSame($first, $second);
        self::assertSame('orders_customer_id_foreign', (new Table('sales.orders'))->nameFor(['customer_id'], 'foreign'));
    }

    public function test_a_table_in_a_schema_is_named_part_by_part(): void
    {
        self::assertStringStartsWith('CREATE TABLE "sales"."orders" (', self::compile('pgsql', static function (Table $table): void {
            $table->id();
        }, 'sales.orders')[0]);
        self::assertSame('DROP TABLE [sales].[orders]', Grammar::for('sqlsrv')->compileDropTable('sales.orders'));
    }

    // ---- altering ------------------------------------------------------------

    private static function change(Table $table): void
    {
        $table->string('reference', 40)->nullable()->unique();
        $table->integer('copies')->default(1);
        $table->dropColumn('notes');
        $table->renameColumn('number', 'code');
        $table->dropIndex('customer_id');
    }

    /** @return array<string, array{string, list<string>}> */
    public static function alterations(): array
    {
        return [
            'mysql' => ['mysql', [
                'DROP INDEX `invoices_customer_id_index` ON `invoices`',
                'ALTER TABLE `invoices` DROP COLUMN `notes`',
                'ALTER TABLE `invoices` RENAME COLUMN `number` TO `code`',
                'ALTER TABLE `invoices` ADD COLUMN `reference` VARCHAR(40) NULL',
                'ALTER TABLE `invoices` ADD COLUMN `copies` INT NOT NULL DEFAULT 1',
                'CREATE UNIQUE INDEX `invoices_reference_unique` ON `invoices` (`reference`)',
            ]],
            'pgsql' => ['pgsql', [
                'DROP INDEX "invoices_customer_id_index"',
                'ALTER TABLE "invoices" DROP COLUMN "notes"',
                'ALTER TABLE "invoices" RENAME COLUMN "number" TO "code"',
                'ALTER TABLE "invoices" ADD COLUMN "reference" VARCHAR(40) NULL',
                'ALTER TABLE "invoices" ADD COLUMN "copies" INTEGER NOT NULL DEFAULT 1',
                'CREATE UNIQUE INDEX "invoices_reference_unique" ON "invoices" ("reference")',
            ]],
            'sqlite' => ['sqlite', [
                'DROP INDEX "invoices_customer_id_index"',
                'ALTER TABLE "invoices" DROP COLUMN "notes"',
                'ALTER TABLE "invoices" RENAME COLUMN "number" TO "code"',
                'ALTER TABLE "invoices" ADD COLUMN "reference" TEXT NULL',
                'ALTER TABLE "invoices" ADD COLUMN "copies" INTEGER NOT NULL DEFAULT 1',
                'CREATE UNIQUE INDEX "invoices_reference_unique" ON "invoices" ("reference")',
            ]],
            // The default's made-up name is looked up and dropped before its column.
            'sqlsrv' => ['sqlsrv', [
                'DROP INDEX [invoices_customer_id_index] ON [invoices]',
                'SET NOCOUNT ON; DECLARE @default SYSNAME, @sql NVARCHAR(MAX); '
                . 'SELECT @default = d.name FROM sys.default_constraints d '
                . 'JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id '
                . "WHERE d.parent_object_id = OBJECT_ID(N'[invoices]') AND c.name = N'notes'; "
                . "IF @default IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [invoices] DROP CONSTRAINT ' + QUOTENAME(@default); EXEC sp_executesql @sql; END; "
                . 'ALTER TABLE [invoices] DROP COLUMN [notes]',
                "EXEC sp_rename N'[invoices].[number]', N'code', N'COLUMN'",
                'ALTER TABLE [invoices] ADD [reference] NVARCHAR(40) NULL',
                'ALTER TABLE [invoices] ADD [copies] INT NOT NULL DEFAULT 1',
                'CREATE UNIQUE INDEX [invoices_reference_unique] ON [invoices] ([reference]) WHERE [reference] IS NOT NULL',
            ]],
        ];
    }

    /**
     * Whatever order the change was described in, what goes goes first, then
     * the renames, then what comes.
     *
     * @param list<string> $expected
     */
    #[DataProvider('alterations')]
    public function test_one_change_is_written_in_each_dialect(string $driver, array $expected): void
    {
        self::assertSame($expected, self::alter($driver, self::change(...)));
    }

    /** @return array<string, array{string, list<string>}> */
    public static function foreignKeyChanges(): array
    {
        $add = static fn(string $q): string => \sprintf(
            'ALTER TABLE %1$sinvoices%2$s ADD CONSTRAINT %1$sinvoices_account_id_foreign%2$s FOREIGN KEY (%1$saccount_id%2$s) '
            . 'REFERENCES %1$saccounts%2$s (%1$sid%2$s) ON DELETE SET NULL ON UPDATE NO ACTION',
            $q[0],
            $q[1],
        );

        return [
            'mysql' => ['mysql', [
                'ALTER TABLE `invoices` DROP FOREIGN KEY `invoices_customer_id_foreign`',
                'ALTER TABLE `invoices` ADD COLUMN `account_id` BIGINT NULL',
                $add('``'),
            ]],
            'pgsql' => ['pgsql', [
                'ALTER TABLE "invoices" DROP CONSTRAINT "invoices_customer_id_foreign"',
                'ALTER TABLE "invoices" ADD COLUMN "account_id" BIGINT NULL',
                $add('""'),
            ]],
            'sqlsrv' => ['sqlsrv', [
                'ALTER TABLE [invoices] DROP CONSTRAINT [invoices_customer_id_foreign]',
                'ALTER TABLE [invoices] ADD [account_id] BIGINT NULL',
                $add('[]'),
            ]],
        ];
    }

    /** @param list<string> $expected */
    #[DataProvider('foreignKeyChanges')]
    public function test_foreign_keys_are_dropped_and_added_by_name(string $driver, array $expected): void
    {
        self::assertSame($expected, self::alter($driver, static function (Table $table): void {
            $table->dropForeign('customer_id');
            $table->bigInteger('account_id')->nullable();
            $table->foreign('account_id')->references('accounts')->onDelete('set null');
        }));
    }

    /** SQLite's ALTER TABLE has no constraints, but a new column can carry its own REFERENCES. */
    public function test_sqlite_writes_a_new_columns_foreign_key_with_the_column(): void
    {
        self::assertSame(
            ['ALTER TABLE "invoices" ADD COLUMN "account_id" INTEGER NULL CONSTRAINT "invoices_account_id_foreign" '
            . 'REFERENCES "accounts" ("id") ON DELETE SET NULL ON UPDATE NO ACTION'],
            self::alter('sqlite', static function (Table $table): void {
                $table->bigInteger('account_id')->nullable();
                $table->foreign('account_id')->references('accounts')->onDelete('set null');
            }),
        );
    }

    /** @return array<string, array{\Closure(Table): mixed, string}> */
    public static function sqliteCannot(): array
    {
        return [
            'drop a foreign key' => [static fn(Table $t) => $t->dropForeign('customer_id'), 'cannot drop the foreign key on "customer_id"'],
            'key a column already there' => [
                static fn(Table $t) => $t->foreign('customer_id')->references('customers'),
                'cannot add a foreign key to the column "customer_id", which is already there',
            ],
            'key a new column with a default' => [static function (Table $t): void {
                $t->bigInteger('account_id')->default(1);
                $t->foreign('account_id')->references('accounts');
            }, 'unless it is nullable with no default'],
        ];
    }

    /** Refused, not done by rebuilding the table -- and refused before anything is sent. */
    #[DataProvider('sqliteCannot')]
    public function test_what_sqlite_cannot_alter_is_refused_with_the_way_round_it(\Closure $define, string $message): void
    {
        try {
            self::alter('sqlite', static function (Table $t) use ($define): void {
                $t->string('first', 10)->nullable();
                $define($t);
            });
            self::fail('SQLite was given a change it has no statement for');
        } catch (DatabaseException $e) {
            self::assertStringContainsString($message, $e->getMessage());
            self::assertStringContainsString('Nothing was run. The way there is a new table', $e->getMessage());
        }
    }

    public function test_an_index_in_a_schema_is_dropped_from_the_schema(): void
    {
        self::assertSame(['DROP INDEX "sales"."orders_placed_at_index"'], self::alter('pgsql', static fn(Table $t) => $t->dropIndex('placed_at'), 'sales.orders'));
        self::assertSame(['DROP INDEX `orders_placed_at_index` ON `sales`.`orders`'], self::alter('mysql', static fn(Table $t) => $t->dropIndex('placed_at'), 'sales.orders'));
    }

    /** SQL Server cannot know whether a column already there may be NULL, so its unique index allows for it. */
    public function test_a_unique_index_on_an_existing_column_on_sql_server_leaves_nulls_out(): void
    {
        self::assertSame(
            ['CREATE UNIQUE INDEX [invoices_number_unique] ON [invoices] ([number]) WHERE [number] IS NOT NULL'],
            self::alter('sqlsrv', static fn(Table $t) => $t->unique('number')),
        );
    }

    /** @return array<string, array{\Closure(Table): mixed, string}> */
    public static function badChanges(): array
    {
        return [
            'a generated key' => [static fn(Table $t) => $t->id(), 'cannot be added to a table that exists'],
            'a column with no value for the rows there' => [static fn(Table $t) => $t->integer('copies'), 'has no value for them'],
            'an index on a column it drops' => [static function (Table $t): void {
                $t->dropColumn('number');
                $t->index('number');
            }, 'which this change drops or renames'],
            'a key on a column it renames' => [static function (Table $t): void {
                $t->renameColumn('customer_id', 'client_id');
                $t->foreign('customer_id')->references('customers');
            }, 'which this change drops or renames'],
            'a column renamed twice' => [static function (Table $t): void {
                $t->renameColumn('number', 'code');
                $t->renameColumn('number', 'ref');
            }, 'renamed twice'],
            'nothing' => [static function (Table $t): void {}, 'the change changes nothing'],
            'an unsafe name' => [static fn(Table $t) => $t->dropColumn('notes; DROP TABLE users'), 'is not a plain name'],
        ];
    }

    #[DataProvider('badChanges')]
    public function test_a_change_that_cannot_be_made_anywhere_is_refused(\Closure $define, string $message): void
    {
        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage($message);

        self::alter('pgsql', $define);
    }

    public function test_a_table_being_created_has_nothing_to_take_away(): void
    {
        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage('dropColumn() belongs in $tables->alter()');

        (new Table('invoices'))->dropColumn('notes');
    }

    public function test_a_driver_without_a_dialect_cannot_alter_tables(): void
    {
        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage('no dialect that writes table structure');

        self::alter('oci', static fn(Table $t) => $t->dropColumn('notes'));
    }

    // ---- what it refuses ----------------------------------------------------

    /** @return array<string, array{\Closure(Table): mixed, string}> */
    public static function refusals(): array
    {
        return [
            'a float default' => [static fn(Table $t) => $t->decimal('price', 8, 2)->default(0.5), 'Write a decimal as a string'],
            'a default on text' => [static fn(Table $t) => $t->text('body')->default('x'), 'cannot have a default'],
            'a default on the key' => [static fn(Table $t) => $t->id()->default(1), 'cannot have a default'],
            'an index on text' => [static fn(Table $t) => $t->text('body')->index(), 'cannot be indexed'],
            'an index on binary' => [static fn(Table $t) => $t->binary('data')->unique(), 'cannot be indexed'],
            'an index on a long string' => [static fn(Table $t) => $t->string('path', 1000)->index(), 'too long to index'],
            'a decimal too precise' => [static fn(Table $t) => $t->decimal('n', 40, 2), 'decimal(40, 2)'],
            'a scale above the precision' => [static fn(Table $t) => $t->decimal('n', 4, 5), 'decimal(4, 5)'],
            'an empty string length' => [static fn(Table $t) => $t->string('s', 0), '1 to 4000'],
            'a string too long' => [static fn(Table $t) => $t->string('s', 5000), '1 to 4000'],
            'a column twice' => [static function (Table $t): void {
                $t->string('name');
                $t->text('name');
            }, 'already has a column "name"'],
            'two keys' => [static function (Table $t): void {
                $t->id();
                $t->id('other');
            }, 'already has a generated key'],
            'a nullable key' => [static fn(Table $t) => $t->id()->nullable(), 'cannot be nullable'],
            'an unknown action' => [static fn(Table $t) => $t->foreign('x')->onDelete('delete everything'), 'is not an action'],
        ];
    }

    /** Refused at the line that asked for it, before anything is compiled. */
    #[DataProvider('refusals')]
    public function test_what_some_database_could_not_do_is_refused_when_asked(\Closure $define, string $message): void
    {
        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage($message);

        $define(new Table('things'));
    }

    /** @return array<string, array{\Closure(Table): mixed, string}> */
    public static function incomplete(): array
    {
        return [
            'no columns' => [static function (Table $t): void {}, 'it has no columns'],
            'a NULL default on a column that cannot hold one' => [static fn(Table $t) => $t->string('s')->default(null), 'not nullable'],
            'an index on a missing column' => [static function (Table $t): void {
                $t->id();
                $t->index('nope');
            }, 'names the column "nope"'],
            'an index over text' => [static function (Table $t): void {
                $t->text('body');
                $t->index('body');
            }, 'cannot be indexed'],
            'a key on a missing column' => [static function (Table $t): void {
                $t->id();
                $t->foreign('customer_id')->references('customers');
            }, 'names the column "customer_id"'],
            'a key pointing nowhere' => [static function (Table $t): void {
                $t->bigInteger('customer_id');
                $t->foreign('customer_id');
            }, 'references nothing'],
            'SET NULL on a column that cannot be NULL' => [static function (Table $t): void {
                $t->bigInteger('customer_id');
                $t->foreign('customer_id')->references('customers')->onDelete('set null');
            }, 'is not nullable'],
            'an unsafe name' => [static fn(Table $t) => $t->string('name; DROP TABLE users'), 'is not a plain name'],
        ];
    }

    /** What needs the whole table is refused when it is compiled -- still before anything runs. */
    #[DataProvider('incomplete')]
    public function test_what_needs_the_whole_table_is_refused_when_it_is_compiled(\Closure $define, string $message): void
    {
        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage($message);

        self::compile('pgsql', $define);
    }

    /** A driver with no dialect has no types to write, and does not guess. */
    public function test_a_driver_without_a_dialect_cannot_create_tables(): void
    {
        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage('no dialect that writes table structure');

        self::compile('oci', static fn(Table $t) => $t->id());
    }

    // ---- on a real database -------------------------------------------------

    public function test_a_table_is_created_used_and_dropped(): void
    {
        $db = $this->sqlite();
        $db->execute('PRAGMA foreign_keys = ON');
        $db->tables()->create('customers', static function (Table $table): void {
            $table->id();
            $table->string('name', 100);
        });
        $db->tables()->create('invoices', self::invoices(...));

        $customer = $db->table('customers')->insert(['name' => 'Ada'], 'id');
        $invoice = $db->table('invoices')->insert(['customer_id' => $customer, 'number' => 'A-1'], 'id');

        self::assertSame(1, $invoice);
        self::assertSame(['number' => 'A-1', 'paid' => 0], $db->table('invoices')->select('number', 'paid')->first());

        foreach ([
            'a second invoice numbered A-1' => ['customer_id' => $customer, 'number' => 'A-1'],
            'an invoice for nobody' => ['customer_id' => 99, 'number' => 'A-2'],
        ] as $refusal => $row) {
            try {
                $db->table('invoices')->insert($row);
                self::fail(\sprintf('the database accepted %s', $refusal));
            } catch (DatabaseException) {
            }
        }

        $db->tables()->drop('invoices');
        self::assertSame(0, $db->scalar("SELECT COUNT(*) FROM sqlite_master WHERE name = 'invoices'"));
    }

    /** The rows already there keep their values through a change, and get the new column's default. */
    public function test_a_table_is_altered_with_its_rows_in_it(): void
    {
        $db = $this->sqlite();
        $db->execute('PRAGMA foreign_keys = ON');
        $db->tables()->create('customers', static function (Table $table): void {
            $table->id();
        });
        $db->tables()->create('invoices', static function (Table $table): void {
            $table->id();
            $table->bigInteger('customer_id')->index();
            $table->string('number', 30);
            $table->text('notes')->nullable();
        });
        $db->table('invoices')->insert(['customer_id' => 7, 'number' => 'A-1', 'notes' => 'gone soon']);

        $db->tables()->alter('invoices', self::change(...));
        $db->tables()->alter('invoices', static function (Table $table): void {
            $table->bigInteger('account_id')->nullable();
            $table->foreign('account_id')->references('customers');
        });

        self::assertSame(
            ['id' => 1, 'customer_id' => 7, 'code' => 'A-1', 'reference' => null, 'copies' => 1, 'account_id' => null],
            $db->table('invoices')->first(),
        );

        $db->table('invoices')->insert(['customer_id' => 7, 'code' => 'A-2']);

        foreach ([
            'a reference used twice' => ['customer_id' => 7, 'code' => 'A-3', 'reference' => 'R'],
            'an account that does not exist' => ['customer_id' => 7, 'code' => 'A-4', 'account_id' => 99],
        ] as $refusal => $row) {
            try {
                $db->table('invoices')->insert($row);
                $db->table('invoices')->insert($row);
                self::fail(\sprintf('the database accepted %s', $refusal));
            } catch (DatabaseException) {
            }
        }
    }

    /** Pretending, the change is written and nothing is sent. */
    public function test_a_pretended_change_changes_nothing(): void
    {
        $db = $this->sqlite();
        $db->tables()->create('invoices', static function (Table $table): void {
            $table->id();
        });

        $tables = $db->tables(pretend: true);
        $tables->alter('invoices', static function (Table $table): void {
            $table->string('number', 30)->nullable();
        });

        self::assertSame([['sql' => 'ALTER TABLE "invoices" ADD COLUMN "number" TEXT NULL', 'raw' => false]], $tables->statements());
        $db->table('invoices')->insert(['id' => 1]);
        self::assertSame(['id' => 1], $db->table('invoices')->first());
    }

    /** A string default is quoted by the driver, so a quote in it stays a quote. */
    public function test_a_default_with_a_quote_in_it_is_written_by_the_driver(): void
    {
        $db = $this->sqlite();
        $db->tables()->create('notes', static function (Table $table): void {
            $table->id();
            $table->string('body')->default("it's '; DROP TABLE notes; --");
        });

        $db->table('notes')->insert(['id' => 1]);

        self::assertSame("it's '; DROP TABLE notes; --", $db->table('notes')->where('id', 1)->first()['body'] ?? null);
    }

    public function test_hand_written_sql_runs_only_on_the_databases_it_names(): void
    {
        $db = $this->sqlite();

        $db->tables()->raw('CREATE TABLE plain (x INTEGER)', 'mysql', 'sqlite');
        self::assertSame(0, $db->table('plain')->count());

        $this->expectException(DatabaseException::class);
        $this->expectExceptionMessage('written for pgsql, and this connection is sqlite. Nothing was run.');

        $db->tables()->raw('CREATE TABLE other (x SERIAL)', 'pgsql');
    }
}
