<?php

declare(strict_types=1);

namespace App\Tests\Unit\System\Systemd;

use App\Engine\System\Systemd\SystemdException;
use App\Engine\System\Systemd\SystemdUnits;
use App\Tests\Support\TestCase;
use PHPUnit\Framework\Attributes\DataProvider;

final class SystemdUnitsTest extends TestCase
{
    private function units(?string $group = null, string $base = '/srv/shop', string $php = '/usr/bin/php8.3'): SystemdUnits
    {
        return SystemdUnits::forApplication($base, 'shop-1a2b3c4d', 'www-data', $group, $php);
    }

    public function test_the_worker_is_a_template_over_the_queue_name(): void
    {
        [$worker] = $this->units()->files();

        self::assertSame('shop-1a2b3c4d-worker@.service', $worker->name);
        self::assertSame(<<<'UNIT'
            # Generated by php laika system:systemd:generate. Regenerate rather than edit.

            [Unit]
            Description=shop-1a2b3c4d queue worker (%i)
            After=network-online.target
            Wants=network-online.target

            [Service]
            User=www-data
            WorkingDirectory=/srv/shop
            ExecStart=/usr/bin/php8.3 /srv/shop/laika queue:work --queue=%i --max-jobs=1000 --max-time=3600
            Restart=always
            RestartSec=1
            NoNewPrivileges=yes
            PrivateTmp=yes

            [Install]
            WantedBy=multi-user.target

            UNIT, $worker->contents);
    }

    public function test_the_scheduler_is_a_oneshot_service_and_a_minutely_timer(): void
    {
        [, $service, $timer] = $this->units()->files();

        self::assertSame('shop-1a2b3c4d-scheduler.service', $service->name);
        self::assertStringContainsString("Type=oneshot\n", $service->contents);
        self::assertStringContainsString("ExecStart=/usr/bin/php8.3 /srv/shop/laika schedule:run\n", $service->contents);
        self::assertStringNotContainsString('[Install]', $service->contents, 'started by the timer, never enabled itself');

        self::assertSame('shop-1a2b3c4d-scheduler.timer', $timer->name);
        self::assertStringContainsString("OnCalendar=*-*-* *:*:00\n", $timer->contents);
        self::assertStringContainsString("Unit=shop-1a2b3c4d-scheduler.service\n", $timer->contents);
        self::assertStringContainsString("WantedBy=timers.target\n", $timer->contents);
    }

    public function test_a_group_is_written_when_given(): void
    {
        [$worker] = $this->units('www-data')->files();

        self::assertStringContainsString("User=www-data\nGroup=www-data\n", $worker->contents);
    }

    /** A space needs quoting, and "%" would otherwise be read as a specifier. */
    public function test_paths_are_quoted_and_escaped_for_systemd(): void
    {
        [$worker] = $this->units(base: '/srv/my shop 100%', php: '/opt/php 8/bin/php')->files();

        self::assertStringContainsString("WorkingDirectory=/srv/my shop 100%%\n", $worker->contents);
        self::assertStringContainsString('ExecStart="/opt/php 8/bin/php" "/srv/my shop 100%%/laika" queue:work --queue=%i', $worker->contents);
    }

    public function test_unit_names(): void
    {
        $units = $this->units();

        self::assertSame('shop-1a2b3c4d-worker@billing.service', $units->worker('billing'));
        self::assertSame('shop-1a2b3c4d-scheduler.timer', $units->schedulerTimer());
        self::assertSame('shop-1a2b3c4d-scheduler.service', $units->schedulerService());
        self::assertSame('shop-1a2b3c4d-worker@.service', $units->workerTemplate());
    }

    public function test_it_knows_its_own_units(): void
    {
        $units = $this->units();

        self::assertTrue($units->owns('shop-1a2b3c4d-scheduler.timer'));
        self::assertTrue($units->owns('shop-1a2b3c4d-scheduler.service'));
        self::assertTrue($units->owns('shop-1a2b3c4d-worker@billing.service'));
        self::assertFalse($units->owns('shop-1a2b3c4d-worker@.service'), 'the template is not a unit to enable');
        self::assertFalse($units->owns('shop-1a2b3c4d-worker@Bad Name.service'));
        self::assertFalse($units->owns('shop-other-worker@default.service'));
        self::assertFalse($units->owns('ssh.service'));
    }

    public function test_a_queue_that_is_not_a_queue_name_is_refused(): void
    {
        $this->expectException(SystemdException::class);
        $this->units()->worker('Billing; rm -rf /');
    }

    /** @return array<string, array{string, string, string, string}> */
    public static function refusals(): array
    {
        return [
            'relative base path' => ['srv/shop', 'shop', 'www-data', '/usr/bin/php'],
            'relative php' => ['/srv/shop', 'shop', 'www-data', 'php'],
            'prefix with a slash' => ['/srv/shop', 'shop/x', 'www-data', '/usr/bin/php'],
            'prefix with an @' => ['/srv/shop', 'shop@x', 'www-data', '/usr/bin/php'],
            'user with a space' => ['/srv/shop', 'shop', 'www data', '/usr/bin/php'],
            'user with a newline' => ['/srv/shop', 'shop', "www\nExecStart=/bin/sh", '/usr/bin/php'],
        ];
    }

    #[DataProvider('refusals')]
    public function test_what_cannot_be_written_safely_is_refused(string $base, string $prefix, string $user, string $php): void
    {
        $this->expectException(SystemdException::class);
        SystemdUnits::forApplication($base, $prefix, $user, null, $php);
    }

    public function test_the_php_binary_defaults_to_this_one_from_the_console(): void
    {
        [, $service] = SystemdUnits::forApplication('/srv/shop', 'shop', 'www-data')->files();

        self::assertStringContainsString('ExecStart=' . \PHP_BINARY . ' ', $service->contents);
    }

    public function test_an_explicit_user_is_kept_for_a_deployment(): void
    {
        [$worker] = SystemdUnits::forDeployment('/srv/shop', 'shop', 'deploy', null, '/usr/bin/php')->files();

        self::assertStringContainsString("User=deploy\n", $worker->contents);
    }
}
